name: check_network
description: Checking Internet and Testing Server availability with just few line.
version: 0.0.2
repository: https://github.com/Vedsaga/check_network
issue_tracker: https://github.com/Vedsaga/check_network/issues

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies: 
  connectivity_plus: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1