name: check_network
description: Checking Internet and Testing Server availability with just few line.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies: 
  connectivity_plus: ^2.3.6
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1